// <auto-generated />
namespace _2013114400_PER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SecondModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201706080715285_SecondModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
